sudo virt-install \
-n GitLab \
--description "GitLab Server" \
--os-type=Linux \
--os-variant=centos7.0 \
--ram=2048 \
--vcpus=2 \
--disk path=/var/lib/libvirt/images/gitlab.x86_64.qcow2,bus=virtio,size=24 \
--graphics vnc \
--network type=bridge,source=br0 \
--boot hd,network,menu=on \
--pxe
