sudo virt-install --import \
-n tower-ubuntu-p51s \
--description "Ansible Tower deployed on p51s and Ubuntu Linux" \
--os-type=linux \
--os-variant=ubuntu16.04 \
--ram=4096 \
--vcpus=2 \
--disk path=/var/lib/libvirt/images/tower-ubuntu-p51s.qcow2,bus=virtio,size=20 \
--graphics vnc \
--network network=vnet_nat1,model=virtio \
--boot hd,network,menu=on 
